Repository nc0fr/conception-application, pull requests merged in 2024-05, with the labels that each got.

#41 Refactor de Joueur et début de l'interface Strategie
  src/main/java/fr/nc0/cda/controleur/ControleurJeuNim.java
  src/main/java/fr/nc0/cda/controleur/ControleurPuissance4.java
  src/main/java/fr/nc0/cda/modele/joueur/Joueur.java
  src/main/java/fr/nc0/cda/modele/joueur/Strategie.java
  src/main/java/fr/nc0/cda/vue/Ihm.java
Labels: enhancement

#42 Reunification des contrôleurs avec le paterne de Patron de Méthode
  src/main/java/fr/nc0/cda/controleur/ControleurJeuNim.java
  src/main/java/fr/nc0/cda/controleur/ControleurNim.java
  src/main/java/fr/nc0/cda/controleur/ControleurPuissance4.java
  src/main/java/fr/nc0/cda/controleur/ControleurTemplate.java
  src/main/java/fr/nc0/cda/main/Main.java
  src/main/java/fr/nc0/cda/modele/puissance4/ChoixJouer.java
Labels: enhancement

#51 + Ajout de la strategie aleatoire pour Nim
  src/main/java/fr/nc0/cda/controleur/ControleurNim.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategieAINimAleatoire.java
Labels: enhancement

#53 Strategie p4 classic v2
  .idea/misc.xml
  src/main/java/fr/nc0/cda/controleur/ControleurPuissance4.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategieAIP4.java
  src/main/java/fr/nc0/cda/modele/puissance4/JeuPuissance4.java
  src/main/java/fr/nc0/cda/modele/puissance4/PlateauPuissance4.java
Labels: bug, enhancement

#65 Début du rapport de l'itération 4
  docs/rendus/iteration4.md
  docs/rendus/mo_iteration4.png
Labels: documentation

#68 La Rotation gauche ne mange plus de pions
  .idea/misc.xml
  src/main/java/fr/nc0/cda/modele/puissance4/PlateauPuissance4.java
Labels: bug

#69 Strategie p4 classic v2
  .idea/misc.xml
  src/main/java/fr/nc0/cda/modele/joueur/StrategieAiPuissance4.java
Labels: bug, enhancement

#70 Renommage des fichiers de stratégie
  src/main/java/fr/nc0/cda/controleur/ControleurNim.java
  src/main/java/fr/nc0/cda/controleur/ControleurPuissance4.java
  src/main/java/fr/nc0/cda/main/Main.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategieNimAiAleatoire.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategieNimAiGagnante.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategieNimHumain.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategiePuissance4AiOptimisee.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategiePuissance4AiSimple.java
  src/main/java/fr/nc0/cda/modele/joueur/StrategiePuissance4Humain.java
Labels: documentation, enhancement

#71 LEs jolies messages !!!
  .idea/misc.xml
  src/main/java/fr/nc0/cda/controleur/ControleurNim.java
  src/main/java/fr/nc0/cda/controleur/ControleurPuissance4.java
  src/main/java/fr/nc0/cda/controleur/ControleurTemplate.java
Labels: enhancement

#72 ollalal le commit
  .idea/misc.xml
  src/main/java/fr/nc0/cda/modele/nim/PlateauNim.java
Labels: enhancement
